theme = 'blowfish'
baseURL = 'https://tonytown6033.github.io/'
title = 'TonyTown Blog'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
summaryLength = 30

[pagination]
pagerSize = 10

[taxonomies]
tag = 'tags'
category = 'categories'
series = 'series'

[outputs]
home = ['HTML', 'RSS', 'JSON']

[params]
colorScheme = 'neno'
defaultAppearance = 'light'
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true
mainSections = ['posts']
disableTextInHeader = false
defaultSocialImage = '/img/blowfish_banner.png'

[params.header]
layout = 'fixed-fill-blur'

[params.footer]
showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[params.homepage]
layout = 'profile'
showRecent = true
showRecentItems = 6
showMoreLink = true
showMoreLinkDest = 'posts'
cardView = false
cardViewScreenWidth = true

[params.article]
showDate = true
showViews = false
showLikes = false
showDateUpdated = false
showAuthor = true
showHero = false
showBreadcrumbs = true
showDraftLabel = true
showPagination = true
showReadingTime = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 8
showTaxonomies = true
sharingLinks = ['twitter', 'telegram', 'reddit', 'email']

[params.list]
showHero = false
showBreadcrumbs = true
showSummary = true
showTableOfContents = false
showCards = false
groupByYear = false
cardView = false
cardViewScreenWidth = true

[languages]

[languages.zh-cn]
languageName = '简体中文'
weight = 1
title = 'TonyTown Blog'

[languages.zh-cn.params]
displayName = '简体中文'
isoCode = 'zh-cn'
rtl = false
dateFormat = '2006-01-02'
description = '技术与生活的时尚博客'

[languages.zh-cn.params.author]
name = 'TonyTown'
headline = '记录代码、生活与灵感'
bio = '在这里持续发布技术笔记与生活记录。'
image = 'img/avatar-wounded-man-new.jpg'
links = [{ github = 'https://github.com/TonyTown6033' }]

[[languages.zh-cn.menu.main]]
name = '文章'
pageRef = 'posts'
weight = 10

[[languages.zh-cn.menu.main]]
name = '标签'
pageRef = 'tags'
weight = 20

[[languages.zh-cn.menu.main]]
identifier = 'github'
pre = 'github'
name = 'GitHub'
url = 'https://github.com/TonyTown6033'
weight = 30

[[languages.zh-cn.menu.footer]]
name = '分类'
pageRef = 'categories'
weight = 10

[markup.goldmark.renderer]
unsafe = true
