baseURL = 'https://tonytown6033.github.io/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
hasCJKLanguage = true
title = 'TonyTown Blog'
theme = 're-terminal'
enableRobotsTXT = true

[pagination]
pagerSize = 8

[params]
contentTypeName = 'posts'
themeColor = 'green'
showMenuItems = 3
showLanguageSelector = false
fullWidthTheme = false
centerTheme = true
autoCover = true
readingTime = true
Toc = true
TocTitle = '目录'
showLastUpdated = false

[languages]
[languages.zh-cn]
languageName = '简体中文'
weight = 1

[languages.zh-cn.params]
title = 'TonyTown Blog'
subtitle = '技术与生活的黑客日志'
owner = 'TonyTown'
keywords = 'blog,tech,life,hacker'
copyright = ''
menuMore = '更多'
readMore = '阅读'
readOtherPosts = '继续阅读'
newerPosts = '更新文章'
olderPosts = '更早文章'
missingContentMessage = '页面不存在...'
missingBackButtonLabel = '返回首页'
minuteReadingTime = '分钟阅读'
words = '字'

[languages.zh-cn.params.logo]
logoText = 'TonyTown@blog:~$'
logoHomeLink = '/'

[[languages.zh-cn.menu.main]]
identifier = 'posts'
name = '文章'
url = '/posts'
weight = 1

[[languages.zh-cn.menu.main]]
identifier = 'github'
name = 'GitHub'
url = 'https://github.com/TonyTown6033'
weight = 2

[markup.goldmark.renderer]
unsafe = true
