baseURL = 'https://tonytown6033.github.io/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
hasCJKLanguage = true
title = 'TonyTown Blog'
theme = 'hugo-theme-stack'
enableRobotsTXT = true

[pagination]
pagerSize = 10

[params]
mainSections = ['posts']
rssFullContent = true

[params.footer]
since = 2026
customText = 'Code and Life by TonyTown'

[params.sidebar]
emoji = '⚡'
subtitle = '记录技术，也记录生活。'

[params.article]
headingAnchor = true
math = false
toc = true
readingTime = true

[params.colorScheme]
toggle = true
default = 'auto'

[params.comments]
enabled = false

[params.widgets]
homepage = [
  { type = 'categories', params = { limit = 10 } },
  { type = 'tag-cloud', params = { limit = 12 } },
]
page = [{ type = 'toc' }]

[[social]]
identifier = 'github'
name = 'GitHub'
url = 'https://github.com/TonyTown6033'

[social.params]
icon = 'brand-github'

[[menu.main]]
identifier = 'home'
name = '首页'
url = '/'
weight = 10

[menu.main.params]
icon = 'home'

[[menu.main]]
identifier = 'posts'
name = '文章'
url = '/posts/'
weight = 20

[menu.main.params]
icon = 'categories'

[markup.goldmark.renderer]
unsafe = true
